// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type ActivityFeed struct {
	ID         int32          `json:"id"`
	ActorID    sql.NullInt32  `json:"actor_id"`
	Action     string         `json:"action"`
	TargetType sql.NullString `json:"target_type"`
	TargetID   sql.NullInt32  `json:"target_id"`
	OrgID      sql.NullInt32  `json:"org_id"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type AppSetting struct {
	Key       string          `json:"key"`
	Value     json.RawMessage `json:"value"`
	Scope     sql.NullString  `json:"scope"`
	UpdatedAt sql.NullTime    `json:"updated_at"`
}

type AuditLog struct {
	ID         int32                 `json:"id"`
	UserID     sql.NullInt32         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   int32                 `json:"entity_id"`
	Metadata   pqtype.NullRawMessage `json:"metadata"`
	CreatedAt  sql.NullTime          `json:"created_at"`
}

type Document struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Content     sql.NullString `json:"content"`
	AuthorID    sql.NullInt32  `json:"author_id"`
	Status      sql.NullString `json:"status"`
	PublishedAt sql.NullTime   `json:"published_at"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Event struct {
	ID        int32                 `json:"id"`
	EventType string                `json:"event_type"`
	UserID    sql.NullInt32         `json:"user_id"`
	Metadata  pqtype.NullRawMessage `json:"metadata"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type FeatureFlag struct {
	Name              string         `json:"name"`
	Description       sql.NullString `json:"description"`
	Enabled           sql.NullBool   `json:"enabled"`
	RolloutPercentage sql.NullInt32  `json:"rollout_percentage"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type MediaAsset struct {
	ID         int32          `json:"id"`
	Name       string         `json:"name"`
	FileUrl    string         `json:"file_url"`
	FileType   sql.NullString `json:"file_type"`
	SizeBytes  sql.NullInt64  `json:"size_bytes"`
	UploadedBy sql.NullInt32  `json:"uploaded_by"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}

type Message struct {
	ID          int32         `json:"id"`
	SenderID    sql.NullInt32 `json:"sender_id"`
	RecipientID sql.NullInt32 `json:"recipient_id"`
	Content     string        `json:"content"`
	ReadAt      sql.NullTime  `json:"read_at"`
	CreatedAt   sql.NullTime  `json:"created_at"`
}

type Metric struct {
	ID         int32                 `json:"id"`
	Name       string                `json:"name"`
	Value      string                `json:"value"`
	Dimensions pqtype.NullRawMessage `json:"dimensions"`
	Timestamp  sql.NullTime          `json:"timestamp"`
}

type Notification struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	Title     string         `json:"title"`
	Content   sql.NullString `json:"content"`
	Type      sql.NullString `json:"type"`
	ReadAt    sql.NullTime   `json:"read_at"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Organization struct {
	ID        int32                 `json:"id"`
	Name      string                `json:"name"`
	Slug      string                `json:"slug"`
	LogoUrl   sql.NullString        `json:"logo_url"`
	Settings  pqtype.NullRawMessage `json:"settings"`
	CreatedAt sql.NullTime          `json:"created_at"`
}

type Project struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	OwnerID     sql.NullInt32  `json:"owner_id"`
	OrgID       sql.NullInt32  `json:"org_id"`
	Status      sql.NullString `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Role struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

type Task struct {
	ID          int32          `json:"id"`
	ProjectID   sql.NullInt32  `json:"project_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	AssigneeID  sql.NullInt32  `json:"assignee_id"`
	Status      sql.NullString `json:"status"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Team struct {
	ID          int32          `json:"id"`
	OrgID       sql.NullInt32  `json:"org_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type TeamMember struct {
	TeamID int32  `json:"team_id"`
	UserID int32  `json:"user_id"`
	Role   string `json:"role"`
}

type User struct {
	ID             int32          `json:"id"`
	Email          string         `json:"email"`
	Name           sql.NullString `json:"name"`
	HashedPassword sql.NullString `json:"hashed_password"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
